### PR TITLE
Added __str__ method to Notfications model and fixed an import error core/settings/__init__.py

### PR DESCRIPTION
**Pull request by whitneyjsmith**
I got the server to run but there were errors on the page

### CODE REVIEW

**Comment by dahjah** [comment]
@whitneyjsmith Thank you! 
A quick note here- The .local import error is actually supposed to be there. (It's cleaner to use a try/except for local settings management than to check for local.py and then import it with importlib if it exists) 
I've updated the Readme with a quick blurb about how it works, and changed around some things to help it make more sense. (and updated the except error type to ensure that we're only running production settings when the file doesn't exist and not anytime else)
Essentially, you can use the local.py.template file to create your own local settings file pointing to your local DB, and using your own Github API credentials, but in order to help keep those creds safe, we don't include local.py in the version control. You can alternatively set environment variables for those items, and run the default production.py settings. :)

So that being said, I can merge this PR in once you roll back the change to settings/__init__.py :)

**Review by dahjah — CHANGES_REQUESTED** [review]
Haha- just found this request changes button. :D
Just need to swap the import in `core/settings/__init__.py` back to `from .local import *` and you'll be golden!

**Comment by whitneyjsmith** [comment]
@dahjah
That makes sense. I reverted the change in core/settings/__init__.py and pushed the changes to my forked repository. Thanks for updating the README! That'll be helpful.

**Review by dahjah — APPROVED** [review]
Thank you! :)

**Pull request merged**
